version: '3.3'
services:
  carbon-databse:
    container_name: carbondb
    image: mysql:latest
    volumes:
      - carbon_sql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3307:3306
volumes:
  carbon_sql:
